services:
  - type: web
    name: civimind-ai
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false # Render will ask you to input this value manually in the dashboard for security
